version: 2.1
jobs:
  cypress_local_tests:
    working_directory: ~/cypress-microsoft-tests
    docker:
      - image: cypress/included:6.0.0
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: npm install
      - run:
          name: Run Cypress tests
          command: npm test
  cypress_browserstack_tests:
    working_directory: ~/cypress-microsoft-tests
    docker:
      - image: cimg/node:current
    steps:
      - checkout
      - run:
          name: Install Browserstack-cypress CLI
          command: sudo npm install -g browserstack-cypress-cli
      - run:
          name: Run Cypress tests on Browserstack
          command: npm run cross-browser-tests
workflows:
  cypress-browserstack-tests:
    jobs: 
      - cypress_local_tests
      - cypress_browserstack_tests:
          requires:
            - cypress_local_tests
